### ISSUE TITLE
class Mod should be in it's own file, and should be able to manage itself

### ISSUE THREAD

**Issue by Everspace** [Danacus/FactorioModManager#1]
In addition, lots of what you're doing to a mod, can be managed by itself.

Consider with the following functions added to the Mod class in NewForm.cs:

            public string FilePath()
            {
                return String.Format(
                    "{0}/Factorio/mods/{1}_{2}.zip",
                    Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData),
                    name,
                    localVersion
                );
            }
            
            public bool Exists()
            {
                return File.Exists(FilePath());
            }
            
            public Delete()
            {
                File.Delete(FilePath());
            }

            public void Uninstall()
            {
                if(installed) {
                    Delete();
                    installed = false;
                }
            }

[NewForm.cs#button4_click](https://github.com/Danacus/FactorioModManager/blob/master/Factorio%20Mod%20Manager/NewForm.cs#L563) becomes a little saner:

        private void button4_Click(object sender, EventArgs e)
        {
            DownloadPrompt prompt = new DownloadPrompt();
            prompt.Show();
            prompt.SetText("Are you sure you want to remove the selected mods?");
            prompt.SetTitle("Delete Mods");
            prompt.SetFinishedCallback(() =>
            {
                prompt.Close();
                List<Mod> selection = new List<Mod>();
                selection = modList.SelectedObjects.Cast<Mod>().ToList();

                foreach (Mod m in selection.ToArray())
                {
                      m.Uninstall()
                }

                finalModList.Clear();
                LoadAllModsInstalled(() => { LoadModList(); });
            });
        }

You've smooshed together everything, so there's no clear separation of concerns. The form should probably just show what's "acutally happening", and you delegate to classes that provide the data to display.

Like your User Data. `class UserData` should have the `LoadUserData()` function in it as something like `.Load(string Path)`, as it's not the concern of the form to load it.

**Comment by Danacus** [comment]
Thanks for the tips, when I start writing the code I always want to make it nice, like you did. But actually I always start copy-pasting massive blocks of code and modify it. I should really stop doing that and make my code better. Putting a Load() function in the Userdata class is a really good idea, I'll remember that for later. Edit: I'll just remember everything you said, you're genius.

**Comment by Danacus** [comment]
Should I continue developing this application, or should I stop, because the one of artentus is actually better.

**Comment by Everspace** [comment]
I'm personally of the belief if you want to develop it, do so. There's nothing wrong with competing products, or as a learning exercise improving what you've written if you're still interested.

Maintenance is 90% the battle in software

**Comment by Danacus** [comment]
You're right, it's a good exercise. I'll improve it like you showed me.

**Comment by Danacus** [comment]
I have improved the code! NewForm.cs size changed from 1000+ lines to 300 lines of code
